### ISSUE TITLE
git clone --recursive fails

### ISSUE THREAD

**Issue by dslater82** [kehrlab/PopIns2#32]
It looks like the submodule gatb-minia-pipeline has an invalid commit reference when doing

git clone --recursive https://github.com/kehrlab/PopIns2.git

fatal: reference is not a tree: 08e3bcd44b088f976ff7e40e3b53df7e72bcda7b
Unable to checkout '08e3bcd44b088f976ff7e40e3b53df7e72bcda7b' in submodule path 'external/gatb-minia-pipeline'

**Comment by Krannich479** [comment]
Hello dslater82, 
thanks for using PopIns2. Unfortunately, I cannot reproduce the error. The commit ID of the gatb-minia-pipeline version is still valid and the commit is still present on Github. I successfully downloaded and built PopIns2 on two different systems given its [install](https://github.com/kehrlab/PopIns2#installation) instructions.

For the time being I propose the following workaround:
```
git clone https://github.com/kehrlab/PopIns2.git
cd PopIns2/external
git clone --recursive https://github.com/GATB/gatb-minia-pipeline
cd ..
mkdir build
make
```

**Comment by dslater82** [comment]
Hi Krannich479,

I originally tried with git version 1.8.3.1 which comes with CentOS 7 and I get the failure that I mentioned earlier.  Now I tried git 2.28.0 and it worked just fine.  When one goes to https://github.com/GATB/gatb-minia-pipeline/tree/08e3bcd44b088f976ff7e40e3b53df7e72bcda7b it says "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository." which is what brought me to thinking the commit doesn't exist.  I do see it  browsing https://github.com/GATB/gatb-minia-pipeline/commits/08e3bcd44b088f976ff7e40e3b53df7e72bcda7b.  I am not sure what is going on.

Somewhat odd behavior somehow but I am able to get it downloaded now.  Thanks for your help.
