### ISSUE TITLE
YAML Error: Expected separator '---'

### ISSUE THREAD

**Issue by bioramen-Blip** [kehrlab/PopIns2#40]
Hello, I encountered a problem while using PopLns2, which was caused by an error in YAML/Loader. pm, resulting in the inability to correctly recognize parameters. May I ask if there is any way to solve it? Thanks!

perl $path/PART_run.pl -i 06.merge_samples.chr4.vcf -o ./test -r Ref.fa -t 2 --force --tmpdir ./tmp
YAML Error: Expected separator '---'
   Code: YAML_PARSE_ERR_NO_SEPARATOR
   Line: 1
   Document: 2
 at ~/lib/YAML/Loader.pm line 88.

**Comment by Krannich479** [comment]
Dear @zwj426 ,
I am not yet convinced that this issue is related to [PopIns2](https://github.com/kehrlab/PopIns2) as this software is neither utilizing Perl scripts nor YAML files. If your issue is about a Perl script, as `PART_run.pl`, I kindly ask you to consult the original author.
