### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by panosioannidis** [kehrlab/PopIns2#41]
I have installed all dependencies correctly and I'm trying to compile Popins2 itself, but I get the following error

```
(base) ubuntu@bcg-vm-1-1:~/Programs/PopIns2$ make
g++ -std=c++14 -DDATE=\""on 2023-07-20 16:13:48"\" -DVERSION=\""0.13.0-14d8595"\" -DSEQAN_HAS_ZLIB=1 -DSEQAN_DISABLE_VERSION_CHECK -W -Wall -pedantic  -Wno-long-long -Wno-variadic-macros -Wno-unused-result -march=native -DMAX_KMER_SIZE=64 -I./external/seqan-library-2.2.0/include/ -O3 -DSEQAN_ENABLE_TESTING=0 -DSEQAN_ENABLE_DEBUG=0 -Wno-implicit-fallthrough -Wno-maybe-uninitialized -DSAMTOOLS=\"samtools\" -DBWA=\"bwa\" -DSICKLE=\"sickle\" -DVELVETH=\"velveth-63\" -DVELVETG=\"velvetg-63\" -DMINIA=\"/home/ubuntu/Programs/PopIns2/external/gatb-minia-pipeline/gatb\" -DSPADES=\"spades\" -c src/ColoredDeBruijnGraph.cpp -o build/ColoredDeBruijnGraph.o
In file included from src/ColoredDeBruijnGraph.h:9,
                 from src/ColoredDeBruijnGraph.cpp:1:
src/UnitigExtension.h:12:10: fatal error: bifrost/ColoredCDBG.hpp: No such file or directory
   12 | #include <bifrost/ColoredCDBG.hpp>      /* has the CCDBG_Data_t template */
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:51: build/ColoredDeBruijnGraph.o] Error 1
```

I followed the instructions in the wiki about Bifrost, but I get the same error.

I saw that you refer to the Bifrost headers and libraries, but I'm not sure which exactly are these files. I'm _guessing_ the library is `libbifrost.so` (located in the same directory as the `bifrost` binary), Am I right? And also, which one is/are the header(s)?

Thanks in advance,
Panos

**Comment by panosioannidis** [comment]
Okay, so, I just managed to compile `PopIns2`!

Generally, I followed the instructions in Q2/A2 from the Troubleshooting section:

https://github.com/kehrlab/PopIns2/wiki/Troubleshooting---FAQ

The additional thing that I had to do was to also symlink the directory containing the Bifrost header files (`*.hpp`) within the root directory of Popins. So, if the PopIns2 directory is at `~/Programs/PopIns2` then while in this directory I ran:

```
ln -s ../bifrost/src ./bifrost
```

assuming, of course, that `~/Programs/bifrost/` is the directory where I installed Bifrost.

**Comment by Krannich479** [comment]
Hello @panosioannidis ,
thanks for using PopIns2! I am glad you sorted this issue out and PopIns2 is working on your side. My reply is a little too late but I still wanted to add to this.
Your original post indicates that the bifrost header and/or library files are not known to the required shell environment variables. I'll look at the README and Wiki again soon and see if I can explain this matter more clearly. I'll explain this here for documentation. On a Linux machine, once you install bifrost with a default settings and including the `make install` command the header and library files will reside within the `/usr/local/include` and `/usr/local/lib`, respectively. These folders are known to the GCC compiler by default. However, executing `make install` is not always permitted, particularly on shared cluster environments. Therefore, you can install bifrost's header and libraries to a non-default location via the  `-DCMAKE_INSTALL_PREFIX=/some/path/` cmake option (explained in bifrost's README->Installation->Advanced). Now, this non-default location is **not** known to GCC.  In this case you'd have to manually add `/some/path/include` and `/some/path/lib` to the respective environment variables, as described in Wiki Q2/A2. I hope this make the procedure I bit more clear.

Finally, I am baffled by your solution to be honest. I searched for answers if either `make` or `gcc` adds the current working directory to the paths detected by gcc but afaik they are not. I don't know why this solution is working for you, but I am glad it does. I just doubt that this solution generalizes 🙃 

Please feel free to come back to the issue section again if you need any further assistance with PopIns2 👍
