### ISSUE TITLE
Output explanation

### ISSUE THREAD

**Issue by panosioannidis** [kehrlab/PopIns2#42]
Hello again,

I managed to run all the Popins2 commands till the `place` ones, as suggested in the Usage/Example sections here:

https://github.com/kehrlab/PopIns2

However, I can't understand which file contains the NRSs, even though it is mentioned that they are output in a fasta file... Are they found in the `assembly_final.contigs.fa` files (generated by the `assemble` command), located in the directory of each sample? And consequently, this would mean that the `supercontigs.fa` file (generated by the `merge` command) is the master collection of all NRSs in all samples. Even though, as far as I remember, the supercontigs are the NRSs + anchors. So, is there a "cleaned" file containing only the NRSs?

Thanks,
Panos

**Comment by Krannich479** [comment]
Hi @panosioannidis ,
technically, both files you mentioned contain NRS sequences. It really depends what you are looking for:

- The contigs in `assembly_final.contigs.fa` files are the result of an assembly of unmapped and poorly aligned NGS reads. Hence, the set of contigs of each individual is, in this case, the set of NRS with a few flanking nucleotides each.
- The `supercontigs.fa` is the result of merging all sets of contigs across all individuals. Hence, it also contains NRS with a few flanking nucleotides each. But the merged contigs, called _supercontigs_ represent the set of NRS from your entire cohort/population.

Does that answer your question? I am not entirely sure what you mean by "cleaned" file containing only the NRS.

**Comment by panosioannidis** [comment]
Thanks a lot Thomas! Yes, you did answer my question.

By "cleaned" I meant the sequence of the NRS without the flanking anchor sequences.

**Comment by Krannich479** [comment]
No, there is no "cleaned" sequences file in that form. The flanking nucleotides up- and downstream of the NRS are important to the PopIns algorithm as they are used to `place` the NRS on the reference genome.
My best advise at this point **only if you are highly interested** in only the NRS (with no flanking nucleotides) is that you might use the final population `insertions.vcf` file. Technically, the breakend format of the "ALT" field can be used to identify and trim the reference nucleotides.

⚠️ However, I really don't encourage this though for one simple reason: Different samples can have a slightly varying precise insertion breakpoint for the same NRS. In any case, if you trim the supercontigs from the flanking nucleotides then you end up with a NRS that only represents a single or a subset of individuals. That somewhat opposes the purpose of PopIns.

**Comment by panosioannidis** [comment]
Thanks for all the information!
